// Generated by https://quicktype.io


export interface IAddress {
    calle:         string;
    pais:          string;
    cp:            number;
    provincia:     string;
    municipio:     string;
    esPrincipal:   boolean;
    esFacturacion: boolean;
}



